// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgJmvAMd324nuuJ73weJ-itTJA0HSC_U',
    appId: '1:673198534571:web:be25c2a91dbfd464f1acee',
    messagingSenderId: '673198534571',
    projectId: 'grocifi-lanka',
    authDomain: 'grocifi-lanka.firebaseapp.com',
    storageBucket: 'grocifi-lanka.firebasestorage.app',
    measurementId: 'G-2ZV395K9DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsNJMM-Z_hvh-DaFnS9AloK_C7fpv6HOQ',
    appId: '1:673198534571:android:0629ea085612b120f1acee',
    messagingSenderId: '673198534571',
    projectId: 'grocifi-lanka',
    storageBucket: 'grocifi-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdxDUXscHEzcXsjX1CY-XxyDarbCLdYA',
    appId: '1:673198534571:ios:3337f18fcf671e2ef1acee',
    messagingSenderId: '673198534571',
    projectId: 'grocifi-lanka',
    storageBucket: 'grocifi-lanka.firebasestorage.app',
    iosBundleId: 'com.example.grocify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUgJmvAMd324nuuJ73weJ-itTJA0HSC_U',
    appId: '1:673198534571:web:be25c2a91dbfd464f1acee',
    messagingSenderId: '673198534571',
    projectId: 'grocifi-lanka',
    authDomain: 'grocifi-lanka.firebaseapp.com',
    storageBucket: 'grocifi-lanka.firebasestorage.app',
    measurementId: 'G-2ZV395K9DH',
  );

}